(ns ca.clojurist.styles.tachyons.styles.debug
  "DEBUG (PESTICIDE)
  Docs: http://tachyons.io/docs/debug/
  This is a partial you have to manually include in your
  build file. It places a different colored outline on
  each element which can help you debug layout issues.
  There is also a handy chrome extension that can
  be found at http://pesticide.io"
  (:require
   [garden.units :refer [px]]))

(def styles
  [[:body {:outline [[(px 1) :solid :#2980B9!important]]}]
   [:article {:outline [[(px 1) :solid :#3498DB!important]]}]
   [:nav {:outline [[(px 1) :solid :#0088C3!important]]}]
   [:aside {:outline [[(px 1) :solid :#33A0CE!important]]}]
   [:section {:outline [[(px 1) :solid :#66B8DA!important]]}]
   [:header {:outline [[(px 1) :solid :#99CFE7!important]]}]
   [:footer {:outline [[(px 1) :solid :#CCE7F3!important]]}]
   [:h1 {:outline [[(px 1) :solid :#162544!important]]}]
   [:h2 {:outline [[(px 1) :solid :#314E6E!important]]}]
   [:h3 {:outline [[(px 1) :solid :#3E5E85!important]]}]
   [:h4 {:outline [[(px 1) :solid :#449BAF!important]]}]
   [:h5 {:outline [[(px 1) :solid :#C7D1CB!important]]}]
   [:h6 {:outline [[(px 1) :solid :#4371D0!important]]}]
   [:main {:outline [[(px 1) :solid :#2F4F90!important]]}]
   [:address {:outline [[(px 1) :solid :#1A2C51!important]]}]
   [:div {:outline [[(px 1) :solid :#036CDB!important]]}]

   [:p {:outline [[(px 1) :solid :#AC050B!important]]}]
   [:hr {:outline [[(px 1) :solid :#FF063F!important]]}]
   [:pre {:outline [[(px 1) :solid :#850440!important]]}]
   [:blockquote {:outline [[(px 1) :solid :#F1B8E7!important]]}]
   [:ol {:outline [[(px 1) :solid :#FF050C!important]]}]
   [:ul {:outline [[(px 1) :solid :#D90416!important]]}]
   [:li {:outline [[(px 1) :solid :#D90416!important]]}]
   [:dl {:outline [[(px 1) :solid :#FD3427!important]]}]
   [:dt {:outline [[(px 1) :solid :#FF0043!important]]}]
   [:dd {:outline [[(px 1) :solid :#E80174!important]]}]
   [:figure {:outline [[(px 1) :solid :#FF00BB!important]]}]
   [:figcaption {:outline [[(px 1) :solid :#BF0032!important]]}]

   [:table {:outline [[(px 1) :solid :#00CC99!important]]}]
   [:caption {:outline [[(px 1) :solid :#37FFC4!important]]}]
   [:thead {:outline [[(px 1) :solid :#98DACA!important]]}]
   [:tbody {:outline [[(px 1) :solid :#64A7A0!important]]}]
   [:tfoot {:outline [[(px 1) :solid :#22746B!important]]}]
   [:tr {:outline [[(px 1) :solid :#86C0B2!important]]}]
   [:th {:outline [[(px 1) :solid :#A1E7D6!important]]}]
   [:td {:outline [[(px 1) :solid :#3F5A54!important]]}]
   [:col {:outline [[(px 1) :solid :#6C9A8F!important]]}]
   [:colgroup {:outline [[(px 1) :solid :#6C9A9D!important]]}]

   [:button {:outline [[(px 1) :solid :#DA8301!important]]}]
   [:datalist {:outline [[(px 1) :solid :#C06000!important]]}]
   [:fieldset {:outline [[(px 1) :solid :#D95100!important]]}]
   [:form {:outline [[(px 1) :solid :#D23600!important]]}]
   [:input {:outline [[(px 1) :solid :#FCA600!important]]}]
   [:keygen {:outline [[(px 1) :solid :#B31E00!important]]}]
   [:label {:outline [[(px 1) :solid :#EE8900!important]]}]
   [:legend {:outline [[(px 1) :solid :#DE6D00!important]]}]
   [:meter {:outline [[(px 1) :solid :#E8630C!important]]}]
   [:optgroup {:outline [[(px 1) :solid :#B33600!important]]}]
   [:option {:outline [[(px 1) :solid :#FF8A00!important]]}]
   [:output {:outline [[(px 1) :solid :#FF9619!important]]}]
   [:progress {:outline [[(px 1) :solid :#E57C00!important]]}]
   [:select {:outline [[(px 1) :solid :#E26E0F!important]]}]
   [:textarea {:outline [[(px 1) :solid :#CC5400!important]]}]

   [:details {:outline [[(px 1) :solid :#33848F!important]]}]
   [:summary {:outline [[(px 1) :solid :#60A1A6!important]]}]
   [:command {:outline [[(px 1) :solid :#438DA1!important]]}]
   [:menu {:outline [[(px 1) :solid :#449DA6!important]]}]

   [:del {:outline [[(px 1) :solid :#BF0000!important]]}]
   [:ins {:outline [[(px 1) :solid :#400000!important]]}]

   [:img {:outline [[(px 1) :solid :#22746B!important]]}]
   [:iframe {:outline [[(px 1) :solid :#64A7A0!important]]}]
   [:embed {:outline [[(px 1) :solid :#98DACA!important]]}]
   [:object {:outline [[(px 1) :solid :#00CC99!important]]}]
   [:param {:outline [[(px 1) :solid :#37FFC4!important]]}]
   [:video {:outline [[(px 1) :solid :#6EE866!important]]}]
   [:audio {:outline [[(px 1) :solid :#027353!important]]}]
   [:source {:outline [[(px 1) :solid :#012426!important]]}]
   [:canvas {:outline [[(px 1) :solid :#A2F570!important]]}]
   [:track {:outline [[(px 1) :solid :#59A600!important]]}]
   [:map {:outline [[(px 1) :solid :#7BE500!important]]}]
   [:area {:outline [[(px 1) :solid :#305900!important]]}]

   [:a {:outline [[(px 1) :solid :#FF62AB!important]]}]
   [:em {:outline [[(px 1) :solid :#800B41!important]]}]
   [:strong {:outline [[(px 1) :solid :#FF1583!important]]}]
   [:i {:outline [[(px 1) :solid :#803156!important]]}]
   [:b {:outline [[(px 1) :solid :#CC1169!important]]}]
   [:u {:outline [[(px 1) :solid :#FF0430!important]]}]
   [:s {:outline [[(px 1) :solid :#F805E3!important]]}]
   [:small {:outline [[(px 1) :solid :#D107B2!important]]}]
   [:abbr {:outline [[(px 1) :solid :#4A0263!important]]}]
   [:q {:outline [[(px 1) :solid :#240018!important]]}]
   [:cite {:outline [[(px 1) :solid :#64003C!important]]}]
   [:dfn {:outline [[(px 1) :solid :#B4005A!important]]}]
   [:sub {:outline [[(px 1) :solid :#DBA0C8!important]]}]
   [:sup {:outline [[(px 1) :solid :#CC0256!important]]}]
   [:time {:outline [[(px 1) :solid :#D6606D!important]]}]
   [:code {:outline [[(px 1) :solid :#E04251!important]]}]
   [:kbd {:outline [[(px 1) :solid :#5E001F!important]]}]
   [:samp {:outline [[(px 1) :solid :#9C0033!important]]}]
   [:var {:outline [[(px 1) :solid :#D90047!important]]}]
   [:mark {:outline [[(px 1) :solid :#FF0053!important]]}]
   [:bdi {:outline [[(px 1) :solid :#BF3668!important]]}]
   [:bdo {:outline [[(px 1) :solid :#6F1400!important]]}]
   [:ruby {:outline [[(px 1) :solid :#FF7B93!important]]}]
   [:rt {:outline [[(px 1) :solid :#FF2F54!important]]}]
   [:rp {:outline [[(px 1) :solid :#803E49!important]]}]
   [:span {:outline [[(px 1) :solid :#CC2643!important]]}]
   [:br {:outline [[(px 1) :solid :#DB687D!important]]}]
   [:wbr {:outline [[(px 1) :solid :#DB175B!important]]}]])
